name: Generate JSON

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Run script
      run: python scripts/generate_json.py

    - name: Commit and push JSON
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add json/
        git commit -m "Mise à jour automatique des fichiers JSON"
        git push